import * as p from '@clack/prompts';
import pc from 'picocolors';
import fs from 'fs';
import path from 'path';
import { exec, spawn } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

// ─── TEMPLATE GENERATOR ───────────────────────────────────────────────────────

function generateTokenFile(answers) {
  const {
    projectName,
    projectDescription,
    componentLibrary,
    styling,
    primaryColor,
    accentColor,
    secondaryColor,
    darkColor,
    neutralDark,
    neutralMid,
    neutralLight,
    fontSans,
    fontMono,
    darkModeSurface,
    darkModeRaised,
  } = answers;

  return `# design-token.md
> Generated by DesignPull — designpull.dev
> This file is your single source of truth. Edit values here, run \`designpull sync\` to push to Figma.

---

## Project

Name: ${projectName}
Description: ${projectDescription}
Component library: ${componentLibrary}
Styling: ${styling}

---

## Token Architecture

Two-tier system:
- **Primitives** — raw values only, no intent encoded
- **Semantic** — intent only, aliases to primitives, no raw values

Theme support: Light / Dark (separate semantic sets)
Responsive support: Desktop / Mobile (typography only)

Flow: Primitive → Semantic → Component
Components never reference primitives directly.

---

## Primitive Tokens

### Colors — Brand
\`\`\`
color/brand/primary:       ${primaryColor}
color/brand/accent:        ${accentColor}
color/brand/secondary:     ${secondaryColor}
color/brand/dark:          ${darkColor}
\`\`\`

### Colors — Neutrals
\`\`\`
color/neutral/900:         ${neutralDark}
color/neutral/500:         ${neutralMid}
color/neutral/100:         ${neutralLight}
color/neutral/white:       #FFFFFF
\`\`\`

### Colors — Feedback
\`\`\`
color/feedback/success:    #629B54
color/feedback/successDark:#275B16
color/feedback/warning:    #EA943E
color/feedback/error:      #A72A3F
\`\`\`

### Spacing
\`\`\`
spacing/1:   4px
spacing/2:   8px
spacing/3:   12px
spacing/4:   16px
spacing/5:   20px
spacing/6:   24px
spacing/8:   32px
spacing/10:  40px
spacing/12:  48px
spacing/16:  64px
\`\`\`

### Size
\`\`\`
size/xs:   24px
size/sm:   32px
size/md:   40px
size/lg:   48px
size/xl:   56px
\`\`\`

### Border Radius
\`\`\`
radius/none:   0px
radius/sm:     4px
radius/md:     8px
radius/lg:     12px
radius/xl:     16px
radius/full:   9999px
\`\`\`

### Border Width
\`\`\`
border/width/thin:     1px
border/width/default:  1.5px
border/width/thick:    2px
\`\`\`

### Elevation
\`\`\`
elevation/sm:  0 1px 2px rgba(0,0,0,0.08)
elevation/md:  0 4px 8px rgba(0,0,0,0.10)
elevation/lg:  0 8px 24px rgba(0,0,0,0.12)
\`\`\`

### Typography
\`\`\`
typography/family/sans:     "${fontSans}"
typography/family/mono:     "${fontMono}"
typography/weight/light:    300
typography/weight/regular:  400
typography/weight/medium:   500
typography/weight/semibold: 600
typography/weight/bold:     700
\`\`\`

---

## Semantic Tokens

All semantic tokens are aliases — no raw values.
Paths must be identical across light and dark sets.

### color/surface
\`\`\`
color/surface/default      light → color/neutral/100       dark → ${darkModeSurface}
color/surface/raised       light → color/neutral/white     dark → ${darkModeRaised}
color/surface/overlay      light → color/neutral/white     dark → color/brand/dark
\`\`\`

### color/text
\`\`\`
color/text/primary         light → color/neutral/900       dark → color/neutral/100
color/text/secondary       light → color/neutral/500       dark → color/brand/secondary
color/text/disabled        light → color/neutral/500       dark → color/neutral/500
color/text/inverse         light → color/neutral/white     dark → color/neutral/900
\`\`\`

### color/border
\`\`\`
color/border/default       light → color/neutral/500       dark → color/neutral/500
color/border/focus         light → color/brand/primary     dark → color/brand/accent
\`\`\`

### color/icon
\`\`\`
color/icon/default         light → color/neutral/900       dark → color/neutral/100
color/icon/subtle          light → color/neutral/500       dark → color/neutral/500
\`\`\`

### color/interactive
\`\`\`
color/interactive/primary        light → color/brand/primary     dark → color/brand/secondary
color/interactive/primaryHover   light → color/brand/dark        dark → color/brand/accent
color/interactive/primaryActive  light → color/brand/dark        dark → color/brand/accent
\`\`\`

### color/feedback
\`\`\`
color/feedback/success     → color/feedback/success
color/feedback/warning     → color/feedback/warning
color/feedback/error       → color/feedback/error
color/feedback/info        light → color/brand/primary    dark → color/brand/accent
\`\`\`

### Spacing aliases
\`\`\`
spacing/xs    → spacing/1    (4px)
spacing/sm    → spacing/2    (8px)
spacing/md    → spacing/4    (16px)
spacing/lg    → spacing/6    (24px)
spacing/xl    → spacing/8    (32px)
spacing/2xl   → spacing/12   (48px)
\`\`\`

### Radius aliases
\`\`\`
radius/interactive  → radius/md
radius/card         → radius/lg
radius/overlay      → radius/xl
\`\`\`

---

## Typography Scale

### Desktop
\`\`\`
hero:      64px / line-height 72 / weight medium
h1:        48px / line-height 56 / weight medium
h2:        36px / line-height 44 / weight medium
h3:        28px / line-height 36 / weight medium
h4:        22px / line-height 30 / weight medium
h5:        18px / line-height 26 / weight medium
h6:        16px / line-height 24 / weight medium
body/lg:   18px / line-height 28 / weight regular
body/md:   16px / line-height 24 / weight regular
body/sm:   14px / line-height 20 / weight regular
label/md:  14px / line-height 20 / weight medium
label/sm:  12px / line-height 16 / weight medium
caption:   12px / line-height 16 / weight regular
code:      14px / line-height 20 / weight regular (${fontMono})
\`\`\`

### Mobile
\`\`\`
hero:      36px / line-height 44 / weight medium
h1:        30px / line-height 38 / weight medium
h2:        24px / line-height 32 / weight medium
h3:        20px / line-height 28 / weight medium
h4:        18px / line-height 26 / weight medium
h5:        16px / line-height 24 / weight medium
h6:        14px / line-height 20 / weight medium
body/lg:   16px / line-height 24 / weight regular
body/md:   16px / line-height 24 / weight regular
body/sm:   14px / line-height 20 / weight regular
label/md:  14px / line-height 20 / weight medium
label/sm:  12px / line-height 16 / weight medium
caption:   12px / line-height 16 / weight regular
code:      13px / line-height 20 / weight regular (${fontMono})
\`\`\`

---

## CSS Custom Property Convention

Pattern: \`--{category}-{subcategory}-{role}\`

\`\`\`css
--color-surface-default
--color-text-primary
--color-interactive-primary
--color-border-focus
--spacing-md
--radius-card
--elevation-sm
--typography-body-md-fontSize
--typography-label-md-fontWeight
\`\`\`

Components consume CSS custom properties only.
No raw hex, px, or hardcoded values in any component file.

---

## Figma Variable Collections

| Collection  | Modes            | Contents                    |
|-------------|------------------|-----------------------------|
| Primitives  | Default          | All raw values              |
| Semantic    | Light / Dark     | All intent tokens, aliased  |
| Typography  | Desktop / Mobile | All type scale values       |

---

## Component Token Map

### Buttons
\`\`\`
background:        color/interactive/primary
background-hover:  color/interactive/primaryHover
text:              color/text/inverse
border-radius:     radius/interactive
padding-x:         spacing/md
padding-y:         spacing/sm
font:              typography/label/md
\`\`\`

### Inputs
\`\`\`
background:        color/surface/raised
border:            color/border/default
border-focus:      color/border/focus
text:              color/text/primary
placeholder:       color/text/secondary
border-radius:     radius/interactive
padding:           spacing/sm spacing/md
font:              typography/body/md
\`\`\`

### Cards
\`\`\`
background:        color/surface/raised
border:            color/border/default
border-radius:     radius/card
shadow:            elevation/sm
padding:           spacing/lg
\`\`\`

### Badges
\`\`\`
background:        color/feedback/{variant}
text:              color/text/inverse
border-radius:     radius/full
padding:           spacing/xs spacing/sm
font:              typography/label/sm
\`\`\`

### Modals
\`\`\`
background:        color/surface/overlay
border-radius:     radius/overlay
shadow:            elevation/lg
padding:           spacing/xl
\`\`\`

---

## Rules DesignPull Enforces

1. Semantic tokens never contain raw values — aliases only
2. Components never reference primitive tokens directly
3. Light and dark semantic sets must have identical token paths
4. Desktop and mobile type scales must have identical token paths
5. body/md fontSize must be 16px in both breakpoints (accessibility)
6. No hardcoded values survive into generated component code
7. Every component fill in Figma is bound to a variable — never hardcoded

---

## Changelog

| Date       | What changed                    |
|------------|---------------------------------|
| ${new Date().toISOString().split('T')[0]} | Generated by designpull init   |
`;
}

// ─── VALIDATION HELPERS ───────────────────────────────────────────────────────

function isValidHex(value) {
  return /^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/.test(value.trim());
}

function validateHex(value) {
  if (!value) return 'Color is required';
  if (!isValidHex(value)) return 'Enter a valid hex color e.g. #2F48C4';
  return;
}

// ─── INIT COMMAND ─────────────────────────────────────────────────────────────

export async function runInit(outputDir = process.cwd()) {
  console.log('');
  p.intro(
    `${pc.bgCyan(pc.black(' DesignPull '))}  ${pc.dim('designpull.dev')}`
  );

  p.log.message(
    pc.dim("Let's set up your design token file. This takes about 2 minutes.\n") +
    pc.dim('You can edit design-token.md any time — run ') +
    pc.cyan('designpull sync') +
    pc.dim(' to push changes to Figma.')
  );

  // ── SECTION 1: Project ──────────────────────────────────────────────────────
  p.log.step(pc.bold('Project'));

  const project = await p.group(
    {
      projectName: () =>
        p.text({
          message: 'Project name',
          placeholder: 'Zemora',
          validate: (v) => (!v ? 'Project name is required' : undefined),
        }),

      projectDescription: () =>
        p.text({
          message: 'One-line description',
          placeholder: 'Enterprise risk assessment platform',
        }),

      componentLibrary: () =>
        p.select({
          message: 'Component library',
          options: [
            { value: 'Chakra UI',  label: 'Chakra UI',  hint: 'recommended' },
            { value: 'Base UI',    label: 'Base UI' },
            { value: 'Radix UI',   label: 'Radix UI' },
            { value: 'shadcn/ui',  label: 'shadcn/ui' },
            { value: 'Custom',     label: 'Custom / none' },
          ],
        }),

      styling: () =>
        p.select({
          message: 'Styling approach',
          options: [
            { value: 'CSS Modules + CSS custom properties', label: 'CSS Modules + CSS custom properties', hint: 'recommended' },
            { value: 'Tailwind CSS',  label: 'Tailwind CSS' },
            { value: 'styled-components', label: 'styled-components' },
            { value: 'CSS custom properties only', label: 'CSS custom properties only' },
          ],
        }),
    },
    { onCancel: () => { p.cancel('Setup cancelled.'); process.exit(0); } }
  );

  // ── SECTION 2: Brand Colors ─────────────────────────────────────────────────
  p.log.step(pc.bold('Brand Colors'));
  p.log.message(pc.dim('These become your primitive color tokens.'));

  const colors = await p.group(
    {
      primaryColor: () =>
        p.text({
          message: 'Primary brand color',
          placeholder: '#2F48C4',
          validate: validateHex,
        }),

      accentColor: () =>
        p.text({
          message: 'Accent color',
          placeholder: '#3CF8F8',
          validate: validateHex,
        }),

      secondaryColor: () =>
        p.text({
          message: 'Secondary color',
          placeholder: '#A3A3FF',
          validate: validateHex,
        }),

      darkColor: () =>
        p.text({
          message: 'Dark brand color (e.g. deep navy, dark teal)',
          placeholder: '#21163A',
          validate: validateHex,
        }),

      neutralDark: () =>
        p.text({
          message: 'Neutral dark (text, headings)',
          placeholder: '#1E272E',
          validate: validateHex,
        }),

      neutralMid: () =>
        p.text({
          message: 'Neutral mid (secondary text, borders)',
          placeholder: '#5C6B7A',
          validate: validateHex,
        }),

      neutralLight: () =>
        p.text({
          message: 'Neutral light (backgrounds, surfaces)',
          placeholder: '#EBF4FC',
          validate: validateHex,
        }),
    },
    { onCancel: () => { p.cancel('Setup cancelled.'); process.exit(0); } }
  );

  // ── SECTION 3: Typography ───────────────────────────────────────────────────
  p.log.step(pc.bold('Typography'));

  const typography = await p.group(
    {
      fontSans: () =>
        p.text({
          message: 'Primary font (sans-serif)',
          placeholder: 'IBM Plex Sans',
          initialValue: 'IBM Plex Sans',
        }),

      fontMono: () =>
        p.text({
          message: 'Monospace font',
          placeholder: 'IBM Plex Mono',
          initialValue: 'IBM Plex Mono',
        }),
    },
    { onCancel: () => { p.cancel('Setup cancelled.'); process.exit(0); } }
  );

  // ── SECTION 4: Dark Mode ────────────────────────────────────────────────────
  p.log.step(pc.bold('Dark Mode'));
  p.log.message(pc.dim('Which brand colors should Figma use for dark mode surfaces?'));

  const darkMode = await p.group(
    {
      darkModeSurface: () =>
        p.select({
          message: 'Dark mode page background',
          options: [
            { value: 'color/brand/dark',      label: 'Dark brand color',    hint: colors.darkColor },
            { value: 'color/neutral/900',      label: 'Neutral dark',        hint: colors.neutralDark },
            { value: 'color/brand/primary',    label: 'Primary brand color', hint: colors.primaryColor },
          ],
        }),

      darkModeRaised: () =>
        p.select({
          message: 'Dark mode card / panel surface',
          options: [
            { value: 'color/brand/dark',       label: 'Dark brand color',    hint: colors.darkColor },
            { value: 'color/neutral/900',       label: 'Neutral dark',        hint: colors.neutralDark },
            { value: 'color/brand/secondary',   label: 'Secondary color',     hint: colors.secondaryColor },
          ],
        }),
    },
    { onCancel: () => { p.cancel('Setup cancelled.'); process.exit(0); } }
  );

  // ── SECTION 5: Figma ────────────────────────────────────────────────────────
  p.log.step(pc.bold('Figma'));
  p.log.message(
    pc.dim('DesignPull needs two API keys to sync tokens:\n\n') +
    pc.bold('1. Figma Personal Access Token\n') +
    pc.dim('   Get at: ') + pc.cyan('figma.com → Account Settings → Security → Personal Access Tokens') + '\n' +
    pc.dim('   Scopes: ') + pc.white('File content (read) + Variables (read/write)') + '\n\n' +
    pc.bold('2. Anthropic API Key\n') +
    pc.dim('   Get at: ') + pc.cyan('console.anthropic.com/settings/keys') + '\n' +
    pc.dim('   Used to parse design-token.md into structured JSON')
  );

  const figma = await p.group(
    {
      figmaFileUrl: () =>
        p.text({
          message: 'Figma file URL',
          placeholder: 'https://www.figma.com/file/AbCdEf123/My-Design-System',
          validate: (v) => {
            if (!v) return 'Figma file URL is required';
            if (!v.includes('figma.com/file/') && !v.includes('figma.com/design/')) {
              return 'Must be a valid Figma file URL (figma.com/file/... or figma.com/design/...)';
            }
          },
        }),

      figmaPat: () =>
        p.password({
          message: 'Figma Personal Access Token (or press Enter to skip)',
          validate: (v) => {
            if (!v || !v.trim()) return undefined; // Allow skipping
            if (!v.startsWith('figd_')) return 'Figma PATs start with figd_ — check your token';
          },
        }),

      anthropicKey: () =>
        p.password({
          message: 'Anthropic API Key (or press Enter to skip)',
          validate: (v) => {
            if (!v || !v.trim()) return undefined; // Allow skipping
            if (!v.startsWith('sk-ant-')) return 'Anthropic API keys start with sk-ant- — check your key';
          },
        }),
    },
    { onCancel: () => { p.cancel('Setup cancelled.'); process.exit(0); } }
  );

  // ── CONFIRM ─────────────────────────────────────────────────────────────────
  const outputPath = path.join(outputDir, 'design-token.md');
  const envPath    = path.join(outputDir, '.env');
  const gitignorePath = path.join(outputDir, '.gitignore');
  const alreadyExists = fs.existsSync(outputPath);

  if (alreadyExists) {
    const overwrite = await p.confirm({
      message: pc.yellow('design-token.md already exists. Overwrite?'),
      initialValue: false,
    });
    if (p.isCancel(overwrite) || !overwrite) {
      p.cancel('Setup cancelled. Existing file preserved.');
      process.exit(0);
    }
  }

  // ── WRITE FILES ──────────────────────────────────────────────────────────────
  const spinner = p.spinner();
  spinner.start('Writing project files');

  // 1. design-token.md
  const allAnswers = { ...project, ...colors, ...typography, ...darkMode };
  const tokenContent = generateTokenFile(allAnswers);
  fs.writeFileSync(outputPath, tokenContent, 'utf-8');

  // 2. .env — extract file key from URL
  const figmaFileKey = extractFigmaKey(figma.figmaFileUrl);
  const envLines = [
    '# DesignPull — generated by designpull init',
    '# Do not commit this file',
    '',
    `FIGMA_FILE_URL=${figma.figmaFileUrl}`,
    `FIGMA_FILE_KEY=${figmaFileKey}`,
    (figma.figmaPat && figma.figmaPat.trim()) ? `FIGMA_ACCESS_TOKEN=${figma.figmaPat}` : 'FIGMA_ACCESS_TOKEN=your_pat_here',
    '',
    '# Anthropic — for Claude token parsing',
    (figma.anthropicKey && figma.anthropicKey.trim()) ? `ANTHROPIC_API_KEY=${figma.anthropicKey}` : 'ANTHROPIC_API_KEY=your_key_here',
  ];
  fs.writeFileSync(envPath, envLines.join('\n'), 'utf-8');

  // 3. .gitignore — ensure .env is excluded
  const gitignoreEntry = '\n# DesignPull\n.env\n.designpull/\n';
  if (fs.existsSync(gitignorePath)) {
    const existing = fs.readFileSync(gitignorePath, 'utf-8');
    if (!existing.includes('.env')) {
      fs.appendFileSync(gitignorePath, gitignoreEntry);
    }
  } else {
    fs.writeFileSync(gitignorePath, gitignoreEntry.trimStart(), 'utf-8');
  }

  spinner.stop('Project files written');

  // ── SECTION 6: Prerequisites & First Sync ──────────────────────────────────
  const hasFigmaPat = figma.figmaPat && figma.figmaPat.trim().length > 0;
  const hasAnthropicKey = figma.anthropicKey && figma.anthropicKey.trim().length > 0;
  const hasAllKeys = hasFigmaPat && hasAnthropicKey;

  if (hasAllKeys) {
    await setupAndRunFirstSync(figma.figmaFileUrl, outputDir);
  }

  // ── NEXT STEPS ──────────────────────────────────────────────────────────────

  const missingKeys = [];
  if (!hasFigmaPat) missingKeys.push({ name: 'Figma PAT', env: 'FIGMA_ACCESS_TOKEN', value: 'figd_...', url: 'figma.com → Settings → Personal Access Tokens' });
  if (!hasAnthropicKey) missingKeys.push({ name: 'Anthropic API Key', env: 'ANTHROPIC_API_KEY', value: 'sk-ant-...', url: 'console.anthropic.com/settings/keys' });

  p.note(
    [
      `${pc.green('✓')} ${pc.bold('design-token.md')} — your token source of truth`,
      `${pc.green('✓')} ${pc.bold('.env')}             — API keys ${hasAllKeys ? pc.green('(configured)') : pc.yellow(`(${missingKeys.length} missing)`)}`,
      `${pc.green('✓')} ${pc.bold('.gitignore')}       — .env excluded from git`,
      '',
      ...(missingKeys.length > 0 ? [
        pc.yellow(`⚠ Missing ${missingKeys.length} API key${missingKeys.length > 1 ? 's' : ''}`),
        ...missingKeys.flatMap(key => [
          `  ${pc.bold(key.name)}:`,
          `    Add to ${pc.bold('.env')}: ${pc.dim(key.env + '=')}${pc.cyan(key.value)}`,
          `    Get at: ${pc.cyan(key.url)}`,
        ]),
        '',
      ] : []),
      pc.dim('Next steps:'),
      `  ${pc.cyan('1.')} Review ${pc.bold('design-token.md')} — tweak any values`,
      ...(missingKeys.length > 0 ? [`  ${pc.cyan('2.')} Add missing API keys to ${pc.bold('.env')} (see above)`] : []),
      `  ${pc.cyan(hasAllKeys ? '2.' : '3.')} Run ${pc.cyan('designpull sync')} to start the MCP server`,
      `  ${pc.cyan(hasAllKeys ? '3.' : '4.')} When prompted, open the ${pc.bold('Desktop Bridge')} plugin in Figma`,
    ].join('\n'),
    'Setup complete'
  );

  p.outro(
    `${pc.dim('Questions? ')}${pc.cyan('designpull.dev/docs')}`
  );
}

// ─── FIRST SYNC ORCHESTRATION ─────────────────────────────────────────────────

async function setupAndRunFirstSync(figmaFileUrl, outputDir) {
  p.log.step(pc.bold('Setup & First Sync'));

  // Step 1: Check figma-console-mcp
  const mcpInstalled = await checkFigmaConsoleMcp();
  if (!mcpInstalled) {
    p.log.warn(
      `${pc.yellow('⚠')} figma-console-mcp not found\n\n` +
      `Install it by running:\n` +
      `  ${pc.cyan('npx -y figma-console-mcp@latest --version')}\n\n` +
      `Or visit: ${pc.cyan('https://docs.figma-console-mcp.southleft.com/setup')}`
    );
    return;
  }

  // Step 2: Check Desktop Bridge plugin
  const pluginPath = await getDesktopBridgePath();
  const hasPlugin = await checkDesktopBridgePlugin(pluginPath);
  if (!hasPlugin) {
    return; // User chose not to continue
  }

  // Step 3: Close Desktop Bridge plugin
  const pluginClosed = await p.confirm({
    message: `${pc.yellow('⚠')} Important: Close the Desktop Bridge plugin in Figma if it's open`,
    initialValue: false,
  });
  if (p.isCancel(pluginClosed) || !pluginClosed) {
    p.cancel('Please close the plugin and run init again.');
    return;
  }

  // Step 4: Clean up zombie processes
  const cleanSpinner = p.spinner();
  cleanSpinner.start('Cleaning up any existing MCP server processes');
  await cleanupMcpProcesses();
  cleanSpinner.stop('✓ Port 9223 is now free');

  // Step 5: Confirm ready for sync
  p.log.message(
    `${pc.bold("🚀 Ready to sync your design tokens to Figma")}\n\n` +
    `${pc.dim("When you press")} ${pc.cyan("y")}${pc.dim(":")}\n` +
    `  ${pc.dim("1. We'll start the MCP server (binds to port 9223)")}\n` +
    `  ${pc.dim("2. Wait for \"Server ready on port 9223\"")}\n` +
    `  ${pc.dim("3. THEN open the Desktop Bridge plugin in Figma")}\n` +
    `  ${pc.dim("4. The sync will complete automatically")}`
  );

  const readyToSync = await p.confirm({
    message: 'Ready to start?',
    initialValue: true,
  });
  if (p.isCancel(readyToSync) || !readyToSync) {
    p.cancel('Sync cancelled. Run designpull sync when ready.');
    return;
  }

  // Step 6: Start sync in background and wait for server
  const syncSpinner = p.spinner();
  syncSpinner.start('Starting MCP server');

  const syncProcess = spawn('npm', ['start', 'sync'], {
    cwd: outputDir,
    stdio: ['ignore', 'pipe', 'pipe'],
    detached: false,
    shell: true,
  });

  // Wait for MCP server to bind to port 9223
  const serverReady = await waitForServerBind(9223, 15000);
  if (!serverReady) {
    syncProcess.kill();
    syncSpinner.stop('✗ Server failed to start on port 9223');
    p.log.error('Please run designpull sync manually and check for errors.');
    return;
  }

  syncSpinner.stop('✓ Server ready on port 9223');

  // Step 7: Prompt to open plugin
  p.log.message(
    `${pc.bold('📱 Now open the Desktop Bridge plugin in Figma')}\n\n` +
    `  ${pc.dim('1. In Figma: Right-click → Plugins → Development → Figma Desktop Bridge')}\n` +
    `  ${pc.dim('2. Leave the plugin window open')}\n\n` +
    `${pc.dim('Waiting for plugin to connect... (this takes ~2 seconds)')}`
  );

  const pluginOpened = await p.confirm({
    message: 'Have you opened the plugin?',
    initialValue: false,
  });
  if (p.isCancel(pluginOpened) || !pluginOpened) {
    syncProcess.kill();
    p.cancel('Sync cancelled. Run designpull sync when ready.');
    return;
  }

  // Step 8: Monitor sync output
  const statusSpinner = p.spinner();
  statusSpinner.start('Syncing variables to Figma');

  let syncOutput = '';
  let syncCompleted = false;

  syncProcess.stdout.on('data', (data) => {
    syncOutput += data.toString();
    // Check for success indicators
    if (syncOutput.includes('created') || syncOutput.includes('success')) {
      syncCompleted = true;
    }
  });

  syncProcess.stderr.on('data', (data) => {
    syncOutput += data.toString();
  });

  // Wait for sync to complete (timeout 60s)
  await new Promise((resolve) => {
    syncProcess.on('exit', (code) => {
      if (code === 0 && syncCompleted) {
        statusSpinner.stop('✓ Successfully synced variables to Figma!');
        // Parse output to show variable counts
        const primitiveMatch = syncOutput.match(/Created collection "Primitives".*created":(\d+)/);
        const semanticMatch = syncOutput.match(/Created collection "Semantic".*created":(\d+)/);
        const typographyMatch = syncOutput.match(/Created collection "Typography".*created":(\d+)/);

        if (primitiveMatch || semanticMatch || typographyMatch) {
          const counts = [];
          if (primitiveMatch) counts.push(`Primitives: ${primitiveMatch[1]} variables`);
          if (semanticMatch) counts.push(`Semantic: ${semanticMatch[1]} variables`);
          if (typographyMatch) counts.push(`Typography: ${typographyMatch[1]} variables`);

          p.log.success(`Created:\n  ${counts.join('\n  ')}`);
        }
      } else {
        statusSpinner.stop('✗ Sync failed');
        p.log.error(`Check the output above for errors.\nExit code: ${code}`);
      }
      resolve();
    });

    // Timeout after 60 seconds
    setTimeout(() => {
      if (!syncCompleted) {
        syncProcess.kill();
        statusSpinner.stop('✗ Sync timed out');
        p.log.error('Sync took too long. Please run designpull sync manually.');
        resolve();
      }
    }, 60000);
  });
}

// Helper: Check if figma-console-mcp is installed
async function checkFigmaConsoleMcp() {
  try {
    await execAsync('npx -y figma-console-mcp@latest --version');
    return true;
  } catch {
    return false;
  }
}

// Helper: Get Desktop Bridge plugin path
async function getDesktopBridgePath() {
  try {
    const { stdout } = await execAsync('npx -y figma-console-mcp@latest --print-path');
    return path.join(stdout.trim(), 'figma-desktop-bridge');
  } catch {
    return null;
  }
}

// Helper: Check if Desktop Bridge plugin is installed
async function checkDesktopBridgePlugin(pluginPath) {
  if (!pluginPath || !fs.existsSync(path.join(pluginPath, 'manifest.json'))) {
    p.log.warn(
      `${pc.yellow('⚠')} Desktop Bridge plugin not found\n\n` +
      `Install it by:\n` +
      `  1. Run: ${pc.cyan('npx -y figma-console-mcp@latest --print-path')}\n` +
      `  2. In Figma Desktop: Plugins → Development → Import plugin from manifest\n` +
      `  3. Navigate to the figma-desktop-bridge/manifest.json file\n\n` +
      `Or visit: ${pc.cyan('https://docs.figma-console-mcp.southleft.com/setup#step-3')}`
    );

    const continueAnyway = await p.confirm({
      message: 'Continue anyway? (You can install the plugin later)',
      initialValue: false,
    });
    return !p.isCancel(continueAnyway) && continueAnyway;
  }
  return true;
}

// Helper: Clean up zombie MCP processes and free port 9223
async function cleanupMcpProcesses() {
  try {
    // Kill all figma-console-mcp processes
    await execAsync('pkill -9 -f figma-console-mcp').catch(() => {});

    // Check if port 9223 is still occupied
    const { stdout } = await execAsync('lsof -i :9223 -P').catch(() => ({ stdout: '' }));
    if (stdout) {
      // Extract PID and kill
      const lines = stdout.split('\n');
      for (const line of lines.slice(1)) { // Skip header
        const parts = line.trim().split(/\s+/);
        if (parts[1]) {
          await execAsync(`kill -9 ${parts[1]}`).catch(() => {});
        }
      }
    }

    // Wait a moment for port to be released
    await new Promise(resolve => setTimeout(resolve, 1000));
  } catch (error) {
    // Ignore cleanup errors
  }
}

// Helper: Wait for MCP server to bind to specific port
async function waitForServerBind(port, timeoutMs) {
  const startTime = Date.now();
  while (Date.now() - startTime < timeoutMs) {
    try {
      const { stdout } = await execAsync(`lsof -i :${port} -P`);
      if (stdout.includes('LISTEN')) {
        return true;
      }
    } catch {
      // Port not bound yet
    }
    await new Promise(resolve => setTimeout(resolve, 500));
  }
  return false;
}

// ─── HELPERS ──────────────────────────────────────────────────────────────────

function extractFigmaKey(url) {
  // Handles both figma.com/file/:key and figma.com/design/:key
  const match = url.match(/figma\.com\/(?:file|design)\/([a-zA-Z0-9]+)/);
  return match ? match[1] : '';
}
