// ─── LOCAL DESIGN TOKEN PARSER ───────────────────────────────────────────────
//
// Deterministic parser for design-token.md files generated by `designpull init`.
// Replaces the Claude API call with a zero-dependency local implementation.
//
// Handles 4 patterns:
//   1. Primitive:  `color/brand/primary: #2F48C4`
//   2. Semantic (light/dark): `color/surface/default light → alias dark → alias`
//   3. Semantic (shared):     `color/feedback/success → color/feedback/success`
//   4. Typography: `hero: 64px / line-height 72 / weight medium (FontName)`

const WEIGHT_MAP = {
  light: 300,
  regular: 400,
  medium: 500,
  semibold: 600,
  bold: 700,
};

const WEIGHT_STYLE_MAP = {
  300: 'Light',
  400: 'Regular',
  500: 'Medium',
  600: 'SemiBold',
  700: 'Bold',
};

// ─── TYPE INFERENCE ──────────────────────────────────────────────────────────

function inferType(value) {
  if (typeof value === 'number') return 'FLOAT';
  const str = String(value).trim();
  if (/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/.test(str)) return 'COLOR';
  if (/^-?\d+(\.\d+)?(px)?$/.test(str)) return 'FLOAT';
  return 'STRING';
}

function parseValue(raw) {
  const str = raw.trim();
  // Strip px suffix for numeric values
  const pxMatch = str.match(/^(-?\d+(?:\.\d+)?)px$/);
  if (pxMatch) return parseFloat(pxMatch[1]);
  // Pure number
  if (/^-?\d+(\.\d+)?$/.test(str)) return parseFloat(str);
  // Strip surrounding quotes
  if ((str.startsWith('"') && str.endsWith('"')) || (str.startsWith("'") && str.endsWith("'"))) {
    return str.slice(1, -1);
  }
  return str;
}

// ─── SECTION EXTRACTION ─────────────────────────────────────────────────────

function extractCodeBlocks(markdown, sectionHeader) {
  const lines = markdown.split('\n');
  let inSection = false;
  let inCodeBlock = false;
  let subsection = '';
  const blocks = [];
  let currentBlock = [];

  for (const line of lines) {
    // Track section headers (## level)
    if (/^## /.test(line)) {
      if (inSection && inCodeBlock) {
        blocks.push({ subsection, lines: currentBlock });
        currentBlock = [];
        inCodeBlock = false;
      }
      inSection = line.includes(sectionHeader);
      continue;
    }

    if (!inSection) continue;

    // Track subsection headers (### level)
    if (/^### /.test(line)) {
      subsection = line.replace(/^### /, '').trim();
      continue;
    }

    // Track code blocks
    if (line.trim().startsWith('```')) {
      if (inCodeBlock) {
        blocks.push({ subsection, lines: currentBlock });
        currentBlock = [];
        inCodeBlock = false;
      } else {
        inCodeBlock = true;
      }
      continue;
    }

    if (inCodeBlock && line.trim()) {
      currentBlock.push(line.trim());
    }
  }

  return blocks;
}

// ─── PRIMITIVES ──────────────────────────────────────────────────────────────

function parsePrimitives(markdown) {
  const blocks = extractCodeBlocks(markdown, 'Primitive Tokens');
  const variables = [];

  for (const block of blocks) {
    for (const line of block.lines) {
      // Pattern: `name: value` (with possible whitespace padding)
      const match = line.match(/^(\S+):\s+(.+)$/);
      if (!match) continue;

      const name = match[1];
      const rawValue = match[2].trim();
      const parsed = parseValue(rawValue);
      const type = inferType(parsed);

      // Generate description from name path
      const parts = name.split('/');
      const description = parts.map(p => p.charAt(0).toUpperCase() + p.slice(1)).join(' ');

      variables.push({
        name,
        type,
        values: { Default: parsed },
        alias: null,
        description,
      });
    }
  }

  return {
    name: 'Primitives',
    modes: ['Default'],
    variables,
  };
}

// ─── SEMANTIC TOKENS ─────────────────────────────────────────────────────────

function parseSemanticTokens(markdown, primitiveLookup) {
  const blocks = extractCodeBlocks(markdown, 'Semantic Tokens');
  const variables = [];

  for (const block of blocks) {
    for (const line of block.lines) {
      let variable;

      // Pattern 1: Light/Dark with separate aliases
      // `name   light → alias1   dark → alias2`
      const lightDarkMatch = line.match(
        /^(\S+)\s+light\s*(?:→|->)+\s*(\S+)\s+dark\s*(?:→|->)+\s*(\S+)/
      );

      if (lightDarkMatch) {
        const [, name, lightRef, darkRef] = lightDarkMatch;
        const lightValue = resolveRef(lightRef, primitiveLookup);
        const darkValue = resolveRef(darkRef, primitiveLookup);
        const type = inferType(lightValue);

        variable = {
          name,
          type,
          values: { Light: lightValue, Dark: darkValue },
          alias: isAlias(lightRef) ? lightRef : null,
          description: descriptionFromName(name),
        };
      } else {
        // Pattern 2: Shared alias (same for both modes)
        // `name   → alias   (optional comment)`
        const sharedMatch = line.match(/^(\S+)\s*(?:→|->)+\s*(\S+)(?:\s+\(.*\))?$/);
        if (!sharedMatch) continue;

        const [, name, ref] = sharedMatch;
        const resolved = resolveRef(ref, primitiveLookup);
        const type = inferType(resolved);

        variable = {
          name,
          type,
          values: { Light: resolved, Dark: resolved },
          alias: isAlias(ref) ? ref : null,
          description: descriptionFromName(name),
        };
      }

      variables.push(variable);
    }
  }

  return {
    name: 'Semantic',
    modes: ['Light', 'Dark'],
    variables,
  };
}

function isAlias(ref) {
  // A reference is an alias if it looks like a token path (contains /)
  return ref.includes('/');
}

function resolveRef(ref, primitiveLookup) {
  // If it's a primitive path, look up its value
  if (primitiveLookup[ref] !== undefined) {
    return primitiveLookup[ref];
  }
  // If it's a raw value (hex, number), parse it directly
  return parseValue(ref);
}

// ─── TYPOGRAPHY ──────────────────────────────────────────────────────────────

function parseTypography(markdown, primitiveLookup) {
  const lines = markdown.split('\n');
  let inSection = false;
  let currentMode = null;
  let inCodeBlock = false;
  const modeEntries = { Desktop: [], Mobile: [] };

  for (const line of lines) {
    if (/^## Typography Scale/.test(line)) {
      inSection = true;
      continue;
    }
    if (inSection && /^## /.test(line) && !/Typography/.test(line)) {
      inSection = false;
      continue;
    }
    if (!inSection) continue;

    if (/^### Desktop/.test(line)) { currentMode = 'Desktop'; continue; }
    if (/^### Mobile/.test(line)) { currentMode = 'Mobile'; continue; }

    if (line.trim().startsWith('```')) {
      inCodeBlock = !inCodeBlock;
      continue;
    }

    if (inCodeBlock && currentMode && line.trim()) {
      modeEntries[currentMode].push(line.trim());
    }
  }

  // Parse entries and merge Desktop + Mobile into unified variables
  const variableMap = new Map(); // name → { fontSize, lineHeight, fontWeight, fontFamily }

  for (const [mode, entries] of Object.entries(modeEntries)) {
    for (const entry of entries) {
      // Pattern: `name: Npx / line-height N / weight NAME (optional FontFamily)`
      const match = entry.match(
        /^(\S+):\s+(\d+(?:\.\d+)?)px\s*\/\s*line-height\s+(\d+(?:\.\d+)?)\s*\/\s*weight\s+(\w+)(?:\s+\(([^)]+)\))?$/
      );
      if (!match) continue;

      const [, name, fontSize, lineHeight, weight, fontFamily] = match;

      if (!variableMap.has(name)) {
        variableMap.set(name, {
          fontSize: { Desktop: null, Mobile: null },
          lineHeight: { Desktop: null, Mobile: null },
          weight,
          fontFamily: fontFamily || null,
        });
      }

      const entry2 = variableMap.get(name);
      entry2.fontSize[mode] = parseFloat(fontSize);
      entry2.lineHeight[mode] = parseFloat(lineHeight);
    }
  }

  // Build variables array
  const variables = [];
  const defaultFont = primitiveLookup['typography/family/sans'] || 'sans-serif';

  for (const [name, data] of variableMap) {
    // fontSize
    variables.push({
      name: `${name}/fontSize`,
      type: 'FLOAT',
      values: { Desktop: data.fontSize.Desktop, Mobile: data.fontSize.Mobile },
      alias: null,
      description: `${descriptionFromName(name)} font size`,
    });

    // lineHeight
    variables.push({
      name: `${name}/lineHeight`,
      type: 'FLOAT',
      values: { Desktop: data.lineHeight.Desktop, Mobile: data.lineHeight.Mobile },
      alias: null,
      description: `${descriptionFromName(name)} line height`,
    });

    // fontWeight (alias to primitive)
    const weightPath = `typography/weight/${data.weight}`;
    const weightValue = WEIGHT_MAP[data.weight] ?? 400;
    variables.push({
      name: `${name}/fontWeight`,
      type: 'FLOAT',
      values: { Desktop: weightValue, Mobile: weightValue },
      alias: primitiveLookup[weightPath] !== undefined ? weightPath : null,
      description: `${descriptionFromName(name)} font weight`,
    });

    // fontFamily (alias to primitive)
    const familyPath = data.fontFamily
      ? 'typography/family/mono'
      : 'typography/family/sans';
    const familyValue = data.fontFamily || defaultFont;
    variables.push({
      name: `${name}/fontFamily`,
      type: 'STRING',
      values: { Desktop: familyValue, Mobile: familyValue },
      alias: primitiveLookup[familyPath] !== undefined ? familyPath : null,
      description: `${descriptionFromName(name)} font family`,
    });
  }

  return {
    name: 'Typography',
    modes: ['Desktop', 'Mobile'],
    variables,
    _variableMap: variableMap,
  };
}

// ─── HELPERS ─────────────────────────────────────────────────────────────────

function descriptionFromName(name) {
  return name
    .split('/')
    .map(p => p.charAt(0).toUpperCase() + p.slice(1))
    .join(' ');
}

// ─── PROJECT META ────────────────────────────────────────────────────────────

function parseProjectMeta(markdown) {
  const lines = markdown.split('\n');
  let inSection = false;
  const meta = { textStyles: false, effectStyles: false };

  for (const line of lines) {
    if (/^## Project/.test(line)) { inSection = true; continue; }
    if (inSection && /^## /.test(line)) break;
    if (!inSection) continue;

    const textMatch = line.match(/^Text styles:\s*(yes|no)/i);
    if (textMatch) meta.textStyles = textMatch[1].toLowerCase() === 'yes';

    const effectMatch = line.match(/^Effect styles:\s*(yes|no)/i);
    if (effectMatch) meta.effectStyles = effectMatch[1].toLowerCase() === 'yes';
  }

  return meta;
}

// ─── ELEVATION EFFECTS ──────────────────────────────────────────────────────

function parseElevationEffects(primitives) {
  const elevationVars = primitives.variables.filter(
    v => v.name.startsWith('elevation/') && v.type === 'STRING'
  );

  return elevationVars.map(v => {
    const raw = v.values.Default;
    // Pattern: "0 1px 2px rgba(0,0,0,0.08)" or "0 4px 8px rgba(0,0,0,0.10)"
    const match = raw.match(
      /^(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)px\s+(-?\d+(?:\.\d+)?)px\s+rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([0-9.]+)\s*\)$/
    );

    if (!match) {
      return { name: v.name, raw, effects: [] };
    }

    const [, offsetX, offsetY, blur, r, g, b, a] = match;
    return {
      name: v.name,
      effects: [{
        type: 'DROP_SHADOW',
        offsetX: parseFloat(offsetX),
        offsetY: parseFloat(offsetY),
        blur: parseFloat(blur),
        r: parseInt(r, 10) / 255,
        g: parseInt(g, 10) / 255,
        b: parseInt(b, 10) / 255,
        a: parseFloat(a),
      }],
    };
  });
}

// ─── TYPOGRAPHY COMPOSITES ──────────────────────────────────────────────────

function buildTypographyComposites(variableMap, defaultFont) {
  const composites = [];

  for (const [name, data] of variableMap) {
    const family = data.fontFamily || defaultFont;
    const weightValue = WEIGHT_MAP[data.weight] ?? 400;
    const fontStyle = WEIGHT_STYLE_MAP[weightValue] || 'Regular';

    for (const mode of ['Desktop', 'Mobile']) {
      composites.push({
        name: `${mode}/${name}`,
        fontSize: data.fontSize[mode],
        lineHeight: data.lineHeight[mode],
        fontWeight: weightValue,
        fontStyle,
        fontFamily: family,
      });
    }
  }

  return composites;
}

// ─── MAIN PARSER ─────────────────────────────────────────────────────────────

export function parseDesignTokens(markdown) {
  // Step 1: Parse project meta
  const meta = parseProjectMeta(markdown);

  // Step 2: Parse primitives and build lookup
  const primitives = parsePrimitives(markdown);
  const primitiveLookup = {};
  for (const v of primitives.variables) {
    primitiveLookup[v.name] = v.values.Default;
  }

  // Step 3: Parse semantic tokens (resolving aliases via lookup)
  const semantic = parseSemanticTokens(markdown, primitiveLookup);

  // Step 4: Parse typography
  const typography = parseTypography(markdown, primitiveLookup);

  // Step 5: Build composites
  const composites = { textStyles: [], elevationStyles: [] };

  if (meta.textStyles) {
    composites.textStyles = buildTypographyComposites(
      typography._variableMap,
      primitiveLookup['typography/family/sans'] || 'sans-serif'
    );
  }

  if (meta.effectStyles) {
    composites.elevationStyles = parseElevationEffects(primitives);
  }

  // Clean up internal property
  delete typography._variableMap;

  return {
    collections: [primitives, semantic, typography],
    meta,
    composites,
  };
}
